### ISSUE TITLE
Add an "update next in line" method to the API

### ISSUE THREAD

**Issue by mscharfstein** [google-org/new-project-ny#118]
Create an API route that pulls the next caller in line, and updates the status to indicate that the call has started. Update the ReservationEvents to include the call start time.

MongoDB relevant docs:
- https://docs.mongodb.com/manual/tutorial/model-data-for-atomic-operations/
- https://docs.mongodb.com/manual/reference/method/db.collection.updateOne/#db.collection.updateOne.
Spring Data MongoDB repository docs:
- https://docs.spring.io/spring-data/mongodb/docs/3.0.0.RELEASE/reference/html/#mongo.repositories

**Comment by marcja** [comment]
Just clarifying terminology based on our design discussion yesterday -- this API "provides an optimistic lock on a reservation" to ensure that multiple operators don't simultaneously attempt to service the same reservation. This lock is different than actually indicating that the "call has started". To indicate that the call has started, append a ReservationEvent of type CONNECTED to the Reservation.

**Comment by mscharfstein** [comment]
@marcja , based on the discussion yesterday and the scope for this week, we "provided the optimistic lock on the reservation" by assuming the (non-real world) assumption that the call was immediately CONNECTED. So, we update to CONNECTED right away. Posted this in more detail in Chat yesterday if its helpful for me to grab
