### ISSUE TITLE
Node "consumer" script to process calls

### ISSUE THREAD

**Issue by mscharfstein** [google-org/new-project-ny#120]
Set up node script that, in a loop: starts the next call (using new route in #118 ), schedules the call to be marked as completed after X minutes, and then after a delay, picks up the next call and starts again:
 - Use useInterval and setTimeout methods in node
 - the length of the call and the number of calls handled per a given time period (which determines how long to wait between picking up each call) should be passed in via the command line. The number of calls handled per a given time period should equal the number of calls created at the beginning of each time period in the producer script (both the number of calls and time period are passed to the producer script)
 - a speedUpFactor should be able to be passed to speed up the simulation time so that it doesn't need to follow wall clock time. this factor will affect how long we wait between picking up each call, and how long the scheduled wait is before marking the call as completed. Note a separate Issue will track this as this is part of stage 2

**Comment by mscharfstein** [comment]
At the time of call completion, I think the agent needs to make multiple PATCH requests (or one PATCH request with multiple changes):
 - the time the call actually started (either could make this call now, or right after initially marking the caller's request as in progress - #118 )
- marking the call as resolved (in our current model, this would include adding a reservation event with "completed" type and time AND adding a "resolution" object with the resolution and time)

**Comment by marcja** [comment]
This can be a single PATCH request, adding both events at once (if that's still a requirement, given our design discussion yesterday about startNextCall...)
