### ISSUE TITLE
Handle "speed up" factor for both consumer and producer scripts

### ISSUE THREAD

**Issue by mscharfstein** [google-org/new-project-ny#125]
- Need to determine how to calculate the following, taking into account the provided speed up factor and the provided time frame in which calls are sent and handled:
      - the simulated time the reservation request is created from the producer script
      - the length of time calls should take
      - the call start and call end times from the consumer script

**Comment by kebrahim** [comment]
not prioritized right now, but we can reopen if/when it does get prioritized
