### ISSUE TITLE
Add FE tests for existing components

### ISSUE THREAD

**Issue by mscharfstein** [google-org/new-project-ny#155]
- [x] Cancel
- [x] Feedback
- [x] Reservation
- [ ] WaitDetails
- [x] Routes

**Comment by mscharfstein** [comment]
Components that do NOT need tests: CancelConfirmation, FAQAccordion, Header, ThankYou

Things to test in each component (not exhaustive necessarily but should capture the majority of things to test):

Cancel:
- Check that the resolution const is sent correctly to the right route (mock axios and test what gets sent there; use Home.test.js as example)
- Check the right route is added to the mocked history object (again, Home.test.js has example)

Feedback:
- Fire events that update "rating" and comment "details" and make sure that the correct info is sent to a mocked axios and the correct route is pushed to mocked history

Reservation:
- Make sure to provide the "id" in the URL params (no example of that in Home.test.js yet)
- Provide props.location.state (would be sent from Home) and check that rendering works as expected:
     - Provide props that includes non-null "resolution" and make sure that Feedback is rendered
     - Provide props that includes null "resolution" and make sure that WaitDetails is rendered with the correct props (that would be sent based on Reservation's state)
- Check that correct call being made to a mocked axios from fetchReservation function; mock the return value from this call (consider moving fetchReservation to its own function to more explicitly "unit test")
- Check that the mocked axios is being called every 10 seconds due to the setInterval
- Test convertReservationToState call returns what is expected

WaitDetails:
- test waitTimeEstimate being rendered as expected in several cases:
      - wait time is greater than 24 hours - check which icon is rendered in addition to the waitTimeEstimate
      - minimum time is only a minute away
      - min and max between 1 and 1.5 hrs
      - min and max between 0 min and 50 min
      - min is 5 min away and max is more than 1 hour away

Routes:
- each path renders the right component

**Comment by kebrahim** [comment]
i'm going to start on Feedback

**Comment by mscharfstein** [comment]
i'm going to start on Cancel

**Comment by kebrahim** [comment]
i'll start on Reservation

**Comment by kebrahim** [comment]
on to Routes next

**Comment by kebrahim** [comment]
will send out a basic WaitDetails that Sumer can fill in with her fixes
