### ISSUE TITLE
GET reservation statistics endpoint

### ISSUE THREAD

**Issue by kebrahim** [google-org/new-project-ny#18]
GET /reservations/{id}/statistics

Calculate information on wait time (first with a random number, later using callers in database from external queueing agent)

https://docs.google.com/document/d/1Cdn9skbefSrG6MgZKFvWvMNiNjm9zVb0LRaq7TIqOD0/edit#bookmark=id.seu75iz0450b

**Comment by marcja** [comment]
Per our discussion, this endpoint is definitely not needed for our demo, and probably not the right design for the final API. According to https://cloud.google.com/apis/design/design_patterns#resource_view, we should instead define a view parameter on /reservations/{id} to return either the short/quick call that does not include the statistics or a longer/slower call that does. It would only make sense to split these if the statistics view were to take so long as to become a long-running operation.
