### ISSUE TITLE
Add support for live reload

### ISSUE THREAD

**Issue by marcja** [google-org/new-project-ny#38]
Spring Boot can automatically restart upon detecting changes by adding a developer dependency on spring-boot-devtools. See https://docs.spring.io/spring-boot/docs/current/reference/html/using-spring-boot.html#using-boot-devtools.

This can be used as is and as a basis for live reload. See https://vaadin.com/docs/v14/flow/workflow/tutorial-spring-boot-live-reload.html.

**Comment by tariqajyusuf** [comment]
According to [the reference docs](https://docs.spring.io/spring-boot/docs/1.5.16.RELEASE/reference/html/using-boot-devtools.html#using-boot-devtools-remote-update), it appears that live reload can be done similarly to a local live reload with a few port openings.

Breakdown of work:

* Include `devtools` into the build dependencies
* Add a remote secret
* Open a port for remote client connections

**Comment by tariqajyusuf** [comment]
Update: Figured out how to include the devtools and add a remote secret, though I'm having a hard time getting the remote application runner starting up on my machine.

**Comment by marcja** [comment]
Is this issue now moot because we're moving to tilt.dev?

**Comment by tariqajyusuf** [comment]
No, @itssumertime is figuring out what additional work needs to be done as per our infra design. We have some kind of live reload right now but Sumer is looking at optimizing it.

**Comment by marcja** [comment]
I'm taking a stab at this today.
