### ISSUE TITLE
In WaitDetails, surface "last refreshed" time and show Refresh button

### ISSUE THREAD

**Issue by mscharfstein** [google-org/new-project-ny#53]
Allow users to refresh their wait details without autorefreshing (bad for battery)

**Comment by egracer** [comment]
Is there a reason that refreshing the page is not desirable?

**Comment by marcja** [comment]
This issue may be obsolete. It came up because we didn't have routing support for React routes on the server, so we either need to use React's hash router or add an in-page refresh button. However we now added the routing support to the server, so this isn't strictly necessary anymore.

**Comment by mscharfstein** [comment]
Yeah, don't think we need this anymore. Will close it!
