### ISSUE TITLE
Reservations API does not provide specific id field

### ISSUE THREAD

**Issue by kebrahim** [google-org/new-project-ny#58]
currently, the id of the Reservation needs to be extracted from response._links.self.href

**Comment by tariqajyusuf** [comment]
My best guess is that there might be some way to propagate the symbols forward to the dev image. Right now the dev image is using the output from `npm run build` which is stripping out the symbols.

**Comment by tariqajyusuf** [comment]
I completely misunderstood this. This requires adjusting the response from the REST API (`/api/v1/reservations`) as a top level JSON field.

**Comment by tariqajyusuf** [comment]
As discussed with @marcja, there are reasons we don't necessarily want to expose ID directly so closing this as won't fix.
