### ISSUE TITLE
Make print steps output atomically

### ISSUE THREAD

**Issue by tariqajyusuf** [google-org/new-project-ny#59]
This isn't a big issue now and can probably go on the backlog of "nice to haves" but when using the group build function (i.e. `./gradlew start` instead of `./gradlew helloworld:start`) the prints can interleave in a way that's messy and hard to read. It would be nice to have those prints atomic when needed.

**Comment by marcja** [comment]
Is there a timeline to simply delete helloworld app?

**Comment by marcja** [comment]
It this issue now moot because we're moving to tilt.dev?

**Comment by tariqajyusuf** [comment]
Yeah this is moot. Closing.
