### ISSUE TITLE
Add catch all re-route to be handled by React

### ISSUE THREAD

**Issue by tariqajyusuf** [google-org/new-project-ny#62]
React allows for dynamic management of pages but requires the embedded Tomcat configuration to allow for rewriting.

CC: @mscharfstein

**Comment by marcja** [comment]
So I found a very straightforward fix for this over the weekend, though it isn't particularly scalable. Basically, we can explicitly add additional routes to the controller that redirects to index.html. The upside is that this becomes a 5m job. The downside is that every time you add a new route to the client, you would also need to add it to the server controller. This is perfect for a) lightweight needs like our demo and b) apps with slowly changing routes.

I did find more involved solutions too that work without having to always update the server, but it may be overkill for our demo this week, taking more time and testing than we ought to put on it.
